### ISSUE TITLE
Modify attachment paths to switch from Windows to Linux fails

### ISSUE THREAD

**Issue by vitlib** [willsALMANJ/Zutilo#110]
Following [https://github.com/willsALMANJ/Zutilo/blob/master/docs/COMMANDS.md](commands) I tried to switch the path from '\' to '/' but all the folders of the path were deleted, leaving the path with only the filename.

**Comment by willsALMANJ** [comment]
Hmmm, that is bad. I am guessing you meant going from `\` to `/`?

**Comment by willsALMANJ** [comment]
I played around the function, and I thought I was able to reproduce what you saw the first time I tried. However, since then, I have not been able to reproduce it. Are you able to reliably reproduce it? I was trying by attaching a file on Linux, using the function to change `/` to `\`, and then using the function again to turn `\` back to `/`.

**Comment by vitlib** [comment]
Yes to both. I did it two times and I'd prefer not to try it again and mess other files.
Besides since I switched to Linux the new attachments have no path in the filename field.
I'm using Zotfile, so maybe that's messing it up.

**Comment by willsALMANJ** [comment]
Yes, the attachments only show the file name without the path in the "filename" field in right pane. I think this is by design. On Linux, it will show the full path for an attachment with a Windows-sytle path because it thinks the full path is just the file name (because it does not recognize `\` as a directory delimiter).

If you use Zutilo's "Show attachment paths" on one of the items that you modified with Zutilo, does it show just a filename or does it show a full path? What about if you right-click and choose "Show File"?

**Comment by vitlib** [comment]
It shows the full path. Show files does not find the file, although I solved the issue linking the old folder in the Zotero base folder.
Anyway, when I tried to reproduce the issue it wasn't consistent.

**Comment by willsALMANJ** [comment]
I think when I thought I reproduced the issue the first time I was just seeing the effect that I described above: the Zotero UI just shows the file name, but on Linux Zotero thinks a complete Windows path is a file name, so it shows the full Windows path. After you change the path to a Linux format, only the file name is shown in the UI, but Zotero still has the whole path stored internally.

By the way, I recommend using relative attachment paths in Zotero if possible. This can be turned on in the "Files and folders" subtab of the Advanced tab in Zotero's preferences. With relative paths, you can switch between machines or just move attachments on a single machine without having to update the attachments items' paths.

**Comment by vitlib** [comment]
> I think when I thought I reproduced the issue the first time I was just seeing the effect that I described above

Yes, it's likely.
I'm using relative paths, not sure if this was the case under Windows. How do you suggest to set it? A link to the storage folder?

**Comment by willsALMANJ** [comment]
I am not sure what you mean by link to the storage folder. You need all of your attachments to be below some common directory. Then you choose that directory in Zotero's preferences and it strips that part off of all your attachments. Whenever Zotero needs to use an attachment path, it then concatenates the current base attachment directory setting with what is stored for the attachment. So you can move the common directory holding all your attachments to a new location and you just need to change this base directory preference in Zotero for all your attachments to work with the new location. Also, because of the way the attachment paths are stored and concatenated, it works on Windows/macOS/Linux with the same Zotero attachment data -- you just have to have the write base directory on each system.

**Comment by vitlib** [comment]
Thank you so much for the kindness. I used the absolute path for a bit in one of my Zotero standalone and it screwed up some links.
