### ISSUE TITLE
Changes to URL icon in Zotero beta break the "Save without attachments" feature

### ISSUE THREAD

**Issue by bwiernik** [willsALMANJ/Zutilo#30]
The recent changes to the behavior of the URL icon in the Zotero beta (https://github.com/zotero/zotero/commit/9a87f1595660a1715f3448172d6ce008e308adec) break the "Save without attachments" feature. There is no longer a right-click menu, and the options don't appear in the new dropdown menu.

**Comment by willsALMANJ** [comment]
Yikes, thanks for the warning. I will have to play with the beta and see what I can do. I would guess that just the interface is broken and that the function itself (and the keyboard shortcut that calls it) still works.

**Comment by bwiernik** [comment]
It looks like the change (or other recent Zotero changes) have also also broken the Firefox context menu options (attach page to Zotero item, attach link to Zotero item). They no longer appear in the context menu or in the Zotero submenu.

**Comment by willsALMANJ** [comment]
I looked at the commit and the relevant Zutilo code a little bit. Modifying the save to Zotero menu and modifying the Firefox context menu are both done in the same setup function (in that order). When the save to Zotero component hits an error, execution of the function stops and so the context menu modification is not applied (but I don't think that part is actually broken). The save button was refactored in Zotero so that its context menu is created dynamically without being given an id. The Zutilo modification tries to access the context menu by its id, so that fails now. I think Zutilo just needs to get the `zotero-toolbar-save-button` element and then get its menupopup child rather than getting the menupopup by id directly. I hope to test this out soon.

**Comment by willsALMANJ** [comment]
I think I have addressed this issue with 7187893b0e858495b9b2e66279c03ca965a2fe11. I can't completely test it because I ran into [a bug with the new Zotero combo button](https://github.com/zotero/zotero/issues/658).

I will try to upload a new xpi to https://github.com/willsALMANJ/Zutilo/releases and https://addons.mozilla.org/en-US/firefox/addon/zutilo-utility-for-zotero/versions/ (in the beta channel). Right now the addons.mozilla.org validator is hanging on the XPI upload, and I haven't figured out how to get GitHub to accept a version of the .xpi file other than the one that addons.mozilla.org produces.

**Comment by willsALMANJ** [comment]
I tested out the Save without attachments feature using the [patch to Zotero](https://github.com/zotero/zotero/issues/661) to fix the bug I mentioned. It now works for me, so I'm closing the issue. If you notice any problems, please reopen the issue.
