### ISSUE TITLE
Feature request: shortcut for "Generate Report from Item…"

### ISSUE THREAD

**Issue by gracile-fr** [willsALMANJ/Zutilo#37]
Would it be feasible?
In Zotero it's Zotero_Report_Interface.loadItemReport(event) but what is the event?

Cf. zoteroPane.xul ; reportInterface.js ; xpcom\report.js

Thanks!

**Comment by willsALMANJ** [comment]
Sure, I think that should be as simple as creating a shortcut for `Zotero_Report_Interface.loadItemReport()`. `event` is passed to `Zotero_Pane.loadURI()` which examines it to see if any meta-keys were pressed when the menu item was clicked on and opens the report in a new tab/window depending on which were pressed. I think we'd just use the default behavior of no meta-keys.

**Comment by gracile-fr** [comment]
Easy, indeed. I've just done it locally.
But how can I trigger <code>Zotero_Report_Interface.loadCollectionReport </code>when a collection, not an item is selected ?

**Comment by willsALMANJ** [comment]
Hmm, `Zotero_Report_Interface.loadCollectionReport()` works for me when a collection is selected. Maybe there is something wrong with the way you are calling it? You should see something in the Browser Console if it isn't working.

**Comment by gracile-fr** [comment]
It's working, but I'd like to have the same shortcut for both options. Depending on the context, it would trigger <code>loadCollectioReport()</code> or <code>loadItemReport()</code>.

**Comment by willsALMANJ** [comment]
You will need to check `document.activeElement` and see if its `id` is `zotero-collections-tree` or `zotero-items-tree` and then call the appropriate function. You might just want to choose one of the two to be the default when neither the pane is focused.

**Comment by gracile-fr** [comment]
Thanks for your help!

**Comment by gracile-fr** [comment]
Is it working for you when Zotero for Firefox is in tab mode ?

**Comment by willsALMANJ** [comment]
No, it's not. I played around with it a little bit but didn't come up with a way to fix it. The tab version of Zotero has given me a lot of trouble. It is loaded inside the tab with the same structure as the version loaded into the browser pane, but the two are distinct objects, so referencing the right one within the right context can be tricky. That's why some of the overlay code is slightly convoluted in zoteroOverlay.js, so that it can be called on both the main browser window's document and the tab's document. I think what is going on right now is that the Zotero_Report_Interface functions are being called in the main browser window and they see that no collection or item is selected in the browser pane because the pane can not be opened when Zotero is in tab mode. The Zotero_Report_Interface in the tab context needs to be referenced instead.

**Comment by willsALMANJ** [comment]
Okay, I looked at it a bit more and I think I have it fixed now in 3a1a90507234a0f60048a18a276dd3259

**Comment by gracile-fr** [comment]
Great, thank you!
