### ISSUE TITLE
Feature request: batch edit selected items

### ISSUE THREAD

**Issue by quickfold** [willsALMANJ/Zutilo#38]
Frequently, I have several items that are book chapters and I want to update a field in all of them - such as adding the city of the publisher. Is there any way (or can it be planned) to copy/paste other fields, or even to have a user-selected group of fields copy/pasted? Or is this what "QuickCopy items to clipboard" is supposed to do? I didn't see any mention of quickcopy in the documentation and I can't figure it out.

Thanks!

**Comment by gracile-fr** [comment]
Batch editing is amongst Zotero (not Zutilo) <a href="https://www.zotero.org/support/requested_features">planned feature</a> (probably after zotero 5.0)
In the meantime, you can try that : http://www.zotero.org/support/dev/client_coding/javascript_api#batch_editing (back-up your library).

As for Quick Copy, it is totally different, see <a href="http://www.zotero.org/support/creating_bibliographies#quick_copy">the docs here</a>.

**Comment by willsALMANJ** [comment]
Hmm, have the developers posted anything more recent than that eight year old Trac ticket that was last updated five years ago? That history doesn't give me much confidence that this feature will be added to Zotero any time soon. However, I think I'd only want to add this to Zutilo if we could come up with a quick, clean way to do it. Doing this properly would involve a decent amount of modification of the Zotero UI and would probably be better implemented in Zotero itself rather than added on with Zutilo.

Perhaps the function could open a new window with a series of input fields, one per field shared amongst all selected items, with any field value not common to all items empty. You could enter text into each field to have it applied to all items when you close the window (with empty fields left unaffected -- though this would prevent you from clearing a field; maybe a special sequence like <> could handle this case).

**Comment by gracile-fr** [comment]
I'm sure you're aware of this but the top priority is API syncing at the moment, then new item types (I think Feeds and Institutional Repositories have been added). Once this is done, as far as I understand (I'm not a dev), features like batch editing will be added. Not soon, for sure…

Last post from @dstillman about batch editing (2 years ago): https://groups.google.com/d/msg/zotero-dev/mZCDH7TO1z0/hGWEQsXs3gIJ
More recently on the forums: https://forums.zotero.org/discussion/35109/allow-editing-fields-of-multiple-entries/?Focus=181663#Comment_181663

**Comment by dstillman** [comment]
Batch editing is the first priority after the new types and fields, FWIW.

**Comment by gracile-fr** [comment]
Thanks, that's good to see that mentioning is useful. "FWIW"!

**Comment by willsALMANJ** [comment]
Ah, thanks for the update, Dan. And seeing "batch editing" called out specifically in that short list of planned features from two years ago shows that it is not forgotten. I think most of the other planned features on that list are either implemented or are in progress (several of them are quite large changes compared to batch editing).

I will leave this issue open for now, but I won't plan on working on it myself. I will merge a patch if someone else doesn't want to wait for batch editing in Zotero.

**Comment by willsALMANJ** [comment]
I am going to count #100 as closing this. If one wants to batch modify a set of items, one can copy one with the new copy functions, edit the copied text to the state that one wants, and then paste it into other items.

There is still room for writing a nice UI for editing multiple items, but Zutilo's features are aimed more at shortcuts and simple functions rather than new UI's. I would leave this open any way, but since batch editing (I assume with a UI) is a planned Zotero feature and no one has tried to implement this in Zutilo over the past four years it doesn't seem likely to happen in Zutilo (if you do implement it -- try to submitting it to Zotero itself first!).
