### ISSUE TITLE
Copying Tags from Clipboard

### ISSUE THREAD

**Issue by 7Moses** [willsALMANJ/Zutilo#52]
Hello,  Thanks for the shared work. I have Tags in a clipboard entry separated by a comma ( - expecting convert comma separated String to Tag list -), the copy(?) does not parse at a comma nor semi-colon,  ... is that correct, Best,

**Comment by willsALMANJ** [comment]
Don't you mean "paste", not "copy"? The copy and past functions use newlines to separate items. They do this because that is the format supported by Zotero. If you have newline delimited list in the clipboard and you paste it into the tag box, all of the items will be added as separate tags. Zotero uses newlines to delimit items because comma and semi-colon are valid characters to use inside of a tag.

**Comment by 7Moses** [comment]
Thanks for the reply; the "Copying Tags from Clipboard" should provide clarity. I used a string as in w,x,y,z will try with the newline delimited list, Best,

**Comment by willsALMANJ** [comment]
Sure, I'm open to suggestions for making it more clear. The documentation for the copy/paste functions is here:

https://github.com/willsALMANJ/Zutilo/blob/master/i18n/en-US/readme/docs/COMMANDS.md

**Comment by 7Moses** [comment]
Thanks for the guidance, Best,
