### ISSUE TITLE
Shortcuts gone/not working

### ISSUE THREAD

**Issue by openmedi** [willsALMANJ/Zutilo#54]
Zotero: 4.0.29.5, Zutilo last Updated 05/09/2016 on OSX.

My shortcuts don't work anymore. In `about:config` they are still there, but not available in Zotero or in the Add-On dialogue.

**Comment by willsALMANJ** [comment]
Is this in the Standalone client? There is a bug in Zutilo 2.0 that prevents it from working with the Standalone client. I am going to try to fix it as soon as possible.

You can downgrade to the previous version of Zutilo in the mean time. The main purpose of Zutilo 2.0 is to provide compatibility fixes for Zotero 5.0. The bug is in the way that Zutilo checks the version of Zotero.

**Comment by willsALMANJ** [comment]
The problem should be fixed now. You can get the new version here:

https://addons.mozilla.org/firefox/downloads/file/436231/zutilo_utility_for_zotero-2.0.1-fx.xpi?src=version-history

before it gets approved by Mozilla for automatic updates.

**Comment by openmedi** [comment]
Seems to be working again, thanks for the quick fix!
