### ISSUE TITLE
2.0.1 stopped working in Palemoon

### ISSUE THREAD

**Issue by glocalglocal** [willsALMANJ/Zutilo#55]
2.0.1 still works fine in Zotero Standalone but disappeared from the context menu in Palemoon 26.2.2 64bit. No error message. Options in Addons works OK.

**Comment by willsALMANJ** [comment]
Hmm, which version were you using in Palemoon before 2.0.1? 1.3.0? What version of Zotero are you using?

I am guessing the problem is similar to Standalone. There the problem was referencing CustomizableUI.jsm. I think Palemoon forked right before the UI change that brought in CustomizableUI.jsm. But the Zotero Firefox addon also uses CustomizableUI.jsm, so I would have thought it would also have a problem with Palemoon.

**Comment by glocalglocal** [comment]
It was indeed 1.3.0 and was upgraded automatically to 2.0.1 across Standalone and Palemoon installations on two different machines. Then it stopped appearing on the context menus of the addons but works fine in Standalone. The Zotero addon version is the old 4.0.22 (it won't upgrade because of compatibility issues with Palemoon). I have the latest Palemoon version 26.2.2. 

From what you are saying, I suspect this may be beyond your control, and I will probably have to uninstall Zutilo 2.0.1 from Palemoon and keep it in Standalone. If that is the case, can't I go back to Zutilo 1.3.0 for Palemoon?

**Comment by willsALMANJ** [comment]
Yes, for Palemoon it is probably best to reinstall 1.3.0 (or this pre-release version: https://github.com/willsALMANJ/Zutilo/releases/tag/1.4.0pre001) and turn off automatic updates. There have only been a few features since 1.3.0; most of the changes are just compatibility changes. I would consider modifying Zutilo so that new versions work with Palemoon, but Zotero is planning to drop support for the Firefox version soon any way, so it would be difficult to make a version of Zutilo that worked with the latest version of Zotero and worked with Palemoon.
