### ISSUE TITLE
"Copy attachment path" does not notify an empty value, so the "last path" may stay in clipboard

### ISSUE THREAD

**Issue by acsr** [willsALMANJ/Zutilo#60]
I use Zutilo 2.0.2 in currently Zotero Standalone 4.0.29.15 on MacOSX 10.11.6.

When you copy an existing functioning path of an item using the Zutilo "Copy attachment path" function you get the full qualified path as text into your clipboard. 

When you apply this function to an item with a non existing or corrupt path, no exception is showing up. Instead the clipboard stays unchanged (which is nice to some point). 

The issue arises when you already have copied another path before, you cannot distinguish easily at once that you get the wrong data. An error should never pass silently.

For me different options can solve the issue:

1. Raise a dialog that asks for user action (confirm/OK)
2. Write the plain error/warning to the clipboard (not nice)
3. empty the clipboard

Some of these options have issues if users want to UI Script the application (for whatever).

So this is an initial hint to the behaviour. Not sure if worth to fix it soon. But keep it for the record.
If there is an API call try to "fish" for return values.

I figured this out with an entry saved using the Zotero Bookmarklet on iOS on a brandnew iPadPro 12" running iOS10. First I thought is was an issue of Papership to load the Snapshot, but finally the Zotero Website, and the MacOSX Standalone Client refuse to load the snapshot.

A bit about my Storage Setup

I use a big 6GB Storage for Zotero groups with enough free space. My personal Storage is synced against a private WebDAV Storage. So I am unsure if Zotero can mix storage when using the bookmarklet. In this case Zotero.org can only store the snapshot by the bookmarklet in their own storage since Zotero.org usually does not know the url and credentials of my WebDav Storage.

**Comment by willsALMANJ** [comment]
Thanks for the report. I think raising a dialog if no useful clipboard data is producced would be the best way to handle this (or show a non-modal notification if that is easy to do). It has been a while since I have thought about this. I think the function was written the way it was because URL attachments do not have paths so nothing is added to the clipboard for them. If no data is generated by the command, then it does nothing rather than clear the clipboard. A better solution might be to screen out URL attachments and then let Zutilo clear the clipboard if a file attachment has an empty path. I probably won't have time to work on this soon, but I will keep it in mind.

**Comment by willsALMANJ** [comment]
Closed by https://github.com/willsALMANJ/Zutilo/commit/e73942ade6c7ff9a2a8fdb4ec3875fd9eb6ee4a1
