### ISSUE TITLE
Add tag shortcut not working

### ISSUE THREAD

**Issue by melsophos** [willsALMANJ/Zutilo#81]
The shortcut "Add a tag" is not working (since few months). It opens correctly the tag panel, but it does not create a new field to enter the tag (as it did before).

Current version of the module is 2.0.3, Zotero is 5.0.34.5 (but if I remember it was already a problem for the version 4 towards the end).

**Comment by willsALMANJ** [comment]
I think this was fixed by https://github.com/willsALMANJ/Zutilo/commit/61c7d818697649474f8680d60354756f8caf164a which was part of version 3.0.0.

Starting with version 3.0.0, Zutilo is distributed on the releases page here (https://github.com/willsALMANJ/Zutilo/releases) rather than on addons.mozilla.org. This was done in order to transition away from addons.mozilla.org before they removed support for XUL extensions like Zutilo which are no longer supported in new versions of Firefox. It is interesting that you are on version 2.0.3 because a final version 2.0.4 was released on addons.mozilla.org in order to notify users of the change. Do you have automatic add-on updates disabled in Zotero?

**Comment by melsophos** [comment]
Thanks a lot for your feedback, the automatic updates were indeed disabled (I think I did it due to a bug in another module and forgot to enable again later). I updated to version 3 and now it works well.

**Comment by willsALMANJ** [comment]
Great. I wanted to make sure there wasn't something blocking the update mechanism that I had missed. The tag related functions are the ones I use the most myself.
