### ISSUE TITLE
"Link to File..." shortcut

### ISSUE THREAD

**Issue by tobiasgerstenberg** [willsALMANJ/Zutilo#83]
A keyboard shortcut for the "Link to File..." option would be great. 

![link_to_file](https://user-images.githubusercontent.com/1675584/37528411-f771e02a-290a-11e8-937e-d3bea0dbb06a.png)

**Comment by gracile-fr** [comment]
What about this: https://github.com/willsALMANJ/Zutilo/blob/master/docs/COMMANDS.md#attachment-functions

**Comment by tobiasgerstenberg** [comment]
i don't think any of these shortcuts correspond to the "Link to File..." functionality. "Link to File..." allows you to add a large number of pdfs, and zotero creates appropriate items by reading in the meta-data (and also renames the pdfs).

**Comment by gracile-fr** [comment]
Please correct me if I'm wrong because I can't try at the moment but, as far as I remember, that's exactly what "Attach link to File" does:
> Attach link to file: Open a file picker dialog for selecting a file to attach to the currently selected item as a linked file attachment.

**Comment by tobiasgerstenberg** [comment]
it's not the same -- for "Link to File...", you don't need any items yet. instead, it creates new items based on the files that you want to link to. and it creates the item names (and file names) based on the meta-data that it reads in from the pdf.

**Comment by gracile-fr** [comment]
Ah yes, indeed, sorry !

**Comment by tobiasgerstenberg** [comment]
any updates on potentially implementing this feature?

**Comment by willsALMANJ** [comment]
It is really hard for me to find time to work on new features for Zutilo (lack of time, lack of motivation because Zotero is supposedly rearchitecting which makes it uncertain if Zutilo will keep working without a lot of updating, Zutilo's lack of unit tests which makes it cumbersome to add new features without breaking something). Still this one and your other one were very simple requests, so i just did them quickly now. They are in master, but I haven't made a new release xpi.

**Comment by tobiasgerstenberg** [comment]
brilliant -- thanks!
