### ISSUE TITLE
Feature request: Add attachment from source folder

### ISSUE THREAD

**Issue by sati-bodhi** [willsALMANJ/Zutilo#98]
Can there be a shortcut for adding attachment from source folder? 

![圖片](https://user-images.githubusercontent.com/7592695/61540402-22e4f480-aa70-11e9-9fdc-e76a217ff35a.png)

**Comment by willsALMANJ** [comment]
Yes, there actually is (#84), but I think I have not made a new release since adding that feature. I will try to do that soon.

**Comment by willsALMANJ** [comment]
Version 3.1.0 has just been published.

**Comment by sati-bodhi** [comment]
The new `Attach new file` function is not functioning...

**Comment by willsALMANJ** [comment]
I tried just now and it worked for me. Can you give more information?

**Comment by sati-bodhi** [comment]
What information do you need? I set the shortcut key `Shift-Cmd-A` but nothing happened when using it on one of my library items except the `Zotero` icon blinked blue when the combination is pressed. 

Zotero version: 5.0.70
Zutilo version: 3.1.0
OS: MacOS Mojave 10.14.2

**Comment by willsALMANJ** [comment]
Great! I'm not sure why the restart was necessary (Zutilo should be able to update without restart), but I"m glad it is working.

Otherwise, I would have asked you to run Zotero from a command line with the `-jsconsole` option and see what error message was reported when you tried to use the shortcut.
